# This is a Compose file to deploy Slashstep Server and PostgreSQL in a pod.
name: slashstep-server

# Adjust these values as needed for your environment.
#
# You or your secret manager needs to create these secrets in the appropriate
# directory before deploying this pod.
secrets:
  postgresql-password:
    file: ./secrets/postgresql-password.txt
  jwt-public-key:
    file: ./secrets/jwt-public-key.pem
  jwt-private-key:
    file: ./secrets/jwt-private-key.pem
  slashstep-admin-password:
    file: ./secrets/slashstep-admin-password.txt
  opensearch-root-ca:
    file: ./secrets/opensearch-root-ca.pem
  opensearch-node-certificate:
    file: ./secrets/opensearch-node-certificate.pem
  opensearch-node-key:
    file: ./secrets/opensearch-node-key.pem
  opensearch-admin-certificate:
    file: ./secrets/opensearch-admin-certificate.pem
  opensearch-admin-key:
    file: ./secrets/opensearch-admin-key.pem

configs:
  slashstep-server-config:
    file: ./slashstep-server.yml

services:

  slashstep-server:
    image: slashstep-server
    build:
      context: .
      dockerfile: ./Containerfile
    ports:
      - "3001:3001"
    expose:
      - "3001"
    secrets:
      - postgresql-password
      - jwt-public-key
      - jwt-private-key
      - slashstep-admin-password
    depends_on:
      - postgresql-server
      - valkey-server
    configs:
      - source: slashstep-server-config
        target: /app/slashstep-server.yml

  postgresql-server:
    image: postgres:18.3
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: slashstep_server
      POSTGRES_PASSWORD_FILE: /run/secrets/postgresql-password
      POSTGRES_DB: slashstep
    volumes:
      - postgresql-data:/var/lib/postgresql
    secrets:
      - postgresql-password

  valkey-server:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data

  opensearch-node-1:
    image: opensearchproject/opensearch:3.6.0
    # command: tail -f /dev/null
    ports:
      - "9200:9200"
      - "9300:9300"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - ./opensearch-config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml:ro
      - ./opensearch-config/opensearch-security/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml:ro
      - ./opensearch-config/opensearch-security/roles.yml:/usr/share/opensearch/config/opensearch-security/roles.yml:ro
      - ./opensearch-config/opensearch-security/roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml:ro
      - ./scripts/setup-opensearch-securityadmin.sh:/usr/share/opensearch/config/setup-opensearch-securityadmin.sh:ro
    environment:
      # TODO: Look into multiple nodes later on.
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - DISABLE_PERFORMANCE_ANALYZER_AGENT=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    secrets:
      - source: opensearch-root-ca
        target: /usr/share/opensearch/config/opensearch-root-ca
      - source: opensearch-node-key
        target: /usr/share/opensearch/config/opensearch-node-key
      - source: opensearch-node-certificate
        target: /usr/share/opensearch/config/opensearch-node-certificate
      - opensearch-admin-certificate
      - opensearch-admin-key
    entrypoint: ["/bin/bash", "/usr/share/opensearch/config/setup-opensearch-securityadmin.sh"]

volumes:
  postgresql-data:
  valkey-data:
  opensearch-data: