info:
  name: List configurations
  type: http
  seq: 2

http:
  method: get
  url: "{{base_url}}/configurations"
  params:
    - name: query
      value: ""
      type: query
      disabled: true

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
