name: Run Rust tests on pull request
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths: 
      - src/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/run-rust-tests-on-pull-request.yml
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile-rust-code:
    name: Compile Rust code
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test --no-run
        env:
          RUSTFLAGS: "-Awarnings"
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2.9.1
        with:
          shared-key: ${{ github.workflow }}-${{ github.ref }}
          cache-all-crates: true

  test-routes:
    name: Test routes
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: compile-rust-code
    strategy:
      matrix:
        route-name: 
          - access-policies
          - action-log-entries
          - actions
          - app-authorization-credentials
          - app-authorizations
          - app-credentials
          - apps
          - configurations
          - delegation-policies
          - field-choices
          - field-values
          - fields
          - groups
          - http-transactions
          - item-connection-types
          - item-connections
          - item-types
          - items
          - iterations
          - membership-invitations
          - memberships
          - milestones
          - oauth-access-tokens
          - projects
          # - routes
          # - server-log-entries
          # - sessions
          # - users
          # - views
          # - workspaces
    steps:
      - uses: actions/checkout@v6.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Restore cached dependencies
        uses: Swatinem/rust-cache@v2
        with:
          save-if: false
          shared-key: ${{ github.workflow }}-${{ github.ref }}
      - name: Install mkcert
        run: |
          MKCERT_VERSION="v1.4.4"
          wget -O mkcert https://github.com/FiloSottile/mkcert/releases/download/${MKCERT_VERSION}/mkcert-${MKCERT_VERSION}-linux-amd64
          chmod +x mkcert
          sudo mv mkcert /usr/local/bin/mkcert
      - name: Install mkcert CA
        run: |
          mkcert -install
      - name: Generate SSL certificates
        run: |
          mkdir tls
          cd tls
          mkcert localhost 127.0.0.1 ::1
          cd ..
      - run: mkdir secrets
      - run: openssl genpkey -algorithm ED25519 -out secrets/jwt-private-key.pem
      - run: openssl pkey -in secrets/jwt-private-key.pem -pubout -out ./secrets/jwt-public-key.pem
      - uses: taiki-e/install-action@v2.75.5
        with:
          tool: nextest@0.9.132
      - run: cargo nextest run routes::${{ matrix.route-name }}
        env:
          JWT_PUBLIC_KEY_PATH: ./secrets/jwt-public-key.pem
          JWT_PRIVATE_KEY_PATH: ./secrets/jwt-private-key.pem
          RUSTFLAGS: "-Awarnings"
          CARGO_TERM_COLOR: always
    
  test-resources:
    name: Test resources
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: compile-rust-code
    strategy:
      matrix:
        resource-name:
          - access_policy
          - action
          - action_log_entry
          - app
          - app_authorization
          - app_authorization_credential
          - app_credential
          - configuration
          - delegation_policy
          - field
          - field_choice
          - field_value
          - group
          - http_transaction
          - item
          - item_connection
          - item_connection_type
          - item_type
          - item_type_icon
          - iteration
          - membership
          - membership_invitation
          - milestone
          - oauth_authorization
          - project
          # - role
          # - server_log_entry
          # - session
          # - status
          # - user
          # - view
          # - view_field
          # - webhook
          # - workspace
    steps:
      - uses: actions/checkout@v6.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Restore cached dependencies
        uses: Swatinem/rust-cache@v2.9.1
        with:
          save-if: false
          shared-key: ${{ github.workflow }}-${{ github.ref }}
      - name: Install mkcert
        run: |
          MKCERT_VERSION="v1.4.4"
          wget -O mkcert https://github.com/FiloSottile/mkcert/releases/download/${MKCERT_VERSION}/mkcert-${MKCERT_VERSION}-linux-amd64
          chmod +x mkcert
          sudo mv mkcert /usr/local/bin/mkcert
      - name: Install mkcert CA
        run: |
          mkcert -install
      - name: Generate SSL certificates
        run: |
          mkdir tls
          cd tls
          mkcert localhost 127.0.0.1 ::1
          cd ..
      - run: mkdir secrets
      - run: openssl genpkey -algorithm ED25519 -out secrets/jwt-private-key.pem
      - run: openssl pkey -in secrets/jwt-private-key.pem -pubout -out ./secrets/jwt-public-key.pem
      - uses: taiki-e/install-action@v2.75.5
        with:
          tool: nextest@0.9.132
      - run: cargo nextest run routes::${{ matrix.resource-name }}
        env:
          JWT_PUBLIC_KEY_PATH: ./secrets/jwt-public-key.pem
          JWT_PRIVATE_KEY_PATH: ./secrets/jwt-private-key.pem
          RUSTFLAGS: "-Awarnings"
          CARGO_TERM_COLOR: always
  