name: Run Rust tests on pull request
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  POSTGRESQL_VERSION: "18.3.0"

jobs:
  check-file-changes:
    name: Check file changes
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    outputs:
      rust-code-changed: ${{ steps.filter.outputs.rust-code-changed }}
    steps:
      - uses: actions/checkout@v6.0.0

      - name: Check for Rust code changes
        id: filter
        uses: dorny/paths-filter@v3.0.0
        with:
          filters: |
            rust-code-changed:
              - 'src/**'
              - 'tests/**'
              - 'Cargo.toml'
              - 'Cargo.lock'
              - '.github/workflows/run-rust-tests-on-pull-request.yml'

  compile-rust-code:
    name: Compile Rust code
    runs-on: ubuntu-latest
    needs: check-file-changes
    if: needs.check-file-changes.outputs.rust-code-changed == 'true'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6.0.0

      - name: Install nextest
        uses: taiki-e/install-action@v2.75.5
        with:
          tool: nextest@0.9.132

      - name: Install PostgreSQL
        run: |
          RUST_HOST=$(rustc -vV | sed -n 's/host: //p')
          mkdir -p ${HOME}/.theseus/postgresql
          wget -qO - https://github.com/theseus-rs/postgresql-binaries/releases/download/${POSTGRESQL_VERSION}/postgresql-${POSTGRESQL_VERSION}-${RUST_HOST}.tar.gz | tar -xz -C ${HOME}/.theseus/postgresql
          mv ${HOME}/.theseus/postgresql/postgresql-${POSTGRESQL_VERSION}-${RUST_HOST} ${HOME}/.theseus/postgresql/${POSTGRESQL_VERSION}

      - name: Generate PostgreSQL password
        run: |
          chmod +x scripts/generate-postgresql-password.sh
          scripts/generate-postgresql-password.sh

      - name: Generate JWT key pair
        run: |
          chmod +x scripts/generate-json-web-token-key-pairs.sh
          scripts/generate-json-web-token-key-pairs.sh

      - name: Generate OpenSearch certificates
        run: |
          chmod +x scripts/generate-opensearch-certificates.sh
          scripts/generate-opensearch-certificates.sh
          ls -l ./secrets

      - name: Generate OpenSearch initial admin password
        run: |
          chmod +x scripts/generate-opensearch-initial-admin-password.sh
          scripts/generate-opensearch-initial-admin-password.sh

      - run: cargo nextest run --no-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache dependencies
        uses: actions/cache/save@v5
        with:
          path: |
            ./secrets
            .env
            ~/.theseus
            ~/.cargo
            ./target
          key: ${{ github.workflow }}-${{ github.ref }}-${{ github.run_id }}

  test-routes:
    name: Test routes
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: compile-rust-code
    strategy:
      matrix:
        route-name: 
          - access_policies
          - action_log_entries
          - actions
          - app_authorization_credentials
          - app_authorizations
          - app_credentials
          - apps
          - configurations
          - delegation_policies
          - field_choices
          - field_values
          - fields
          - groups
          - http_transactions
          - item_connection_types
          - item_connections
          - item_types
          - item_type_icons
          - items
          - iterations
          - membership_invitations
          - memberships
          - milestones
          - oauth_access_tokens
          - projects
          - roles
          # - server_log_entries
          - sessions
          - statuses
          - users
          - views
          - view_fields
          - workspaces
    steps:

      - uses: actions/checkout@v6.0.0

      - name: Restore cached dependencies
        uses: actions/cache/restore@v5
        with:
          path: |
            .env
            ./secrets
            ~/.theseus
            ~/.cargo
            ./target
          key: ${{ github.workflow }}-${{ github.ref }}-${{ github.run_id }}

      - name: Set up Redis
        uses: shogo82148/actions-setup-redis@v1.51.0
        with:
          redis-version: "8.6.3"
          auto-start: "false"

      - name: Set up OpenSearch cluster
        run: docker compose -f ./compose.yaml up -d opensearch-node-1

      - name: Wait for OpenSearch to be ready
        run: |
          until curl --cacert ./secrets/opensearch-root-ca.pem --cert ./secrets/opensearch-admin-certificate.pem --key ./secrets/opensearch-admin-key.pem https://localhost:9200 > /dev/null; do
            echo "Waiting for OpenSearch to be ready..."
            sleep 5
          done

      - run: cargo nextest run --no-tests pass --test integration_tests -E 'test(routes::${{ matrix.route-name }}::)'
        env:
          SLASHSTEP_JWT_PUBLIC_KEY_PATH: ./secrets/jwt-public-key.pem
          SLASHSTEP_JWT_PRIVATE_KEY_PATH: ./secrets/jwt-private-key.pem
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_TERM_COLOR: always
    
  test-resources:
    name: Test resources
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: compile-rust-code
    strategy:
      matrix:
        resource-name:
          - access_policy
          - action
          - action_log_entry
          - app
          - app_authorization
          - app_authorization_credential
          - app_credential
          - configuration
          - delegation_policy
          - field
          - field_choice
          - field_value
          - group
          - http_transaction
          - item
          - item_connection
          - item_connection_type
          - item_type
          - item_type_icon
          - iteration
          - membership
          - membership_invitation
          - milestone
          - oauth_authorization
          - project
          - role
          # - server_log_entry
          - session
          - status
          - user
          - view
          - view_field
          # - webhook
          - workspace
    steps:

      - uses: actions/checkout@v6.0.0
      
      - name: Restore cached dependencies
        uses: actions/cache/restore@v5
        with:
          path: |
            ./secrets
            .env
            ~/.theseus
            ~/.cargo
            ./target
          key: ${{ github.workflow }}-${{ github.ref }}-${{ github.run_id }}

      - name: Set up OpenSearch cluster
        run: docker compose -f ./compose.yaml up -d opensearch-node-1

      - name: Wait for OpenSearch to be ready
        run: |
          until curl --cacert ./secrets/opensearch-root-ca.pem --cert ./secrets/opensearch-admin-certificate.pem --key ./secrets/opensearch-admin-key.pem https://localhost:9200 > /dev/null; do
            docker compose logs --tail 100 opensearch-node-1
            echo "Waiting for OpenSearch to be ready..."
            sleep 5
          done

      - name: Set up Redis
        uses: shogo82148/actions-setup-redis@v1.51.0
        with:
          redis-version: "8.6.3"
          auto-start: "false"

      - run: cargo nextest run --no-tests pass --test integration_tests -E 'test(resources::${{ matrix.resource-name }}::)'
        env:
          SLASHSTEP_JWT_PUBLIC_KEY_PATH: ./secrets/jwt-public-key.pem
          SLASHSTEP_JWT_PRIVATE_KEY_PATH: ./secrets/jwt-private-key.pem
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_TERM_COLOR: always
  
  # This job is here for branch protection rules.
  # If GitHub adds a feature to require all jobs from matrix strategies to pass, then we can remove this job and make those test jobs required instead.
  announce-success:
    name: Announce success
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: [test-routes, test-resources, check-file-changes]
    if: always()
    steps:
      - name: Check results
        if: needs.check-file-changes.outputs.rust-code-changed == 'true' && (needs.test-routes.result != 'success' || needs.test-resources.result != 'success')
        run: |
          echo "One or more test jobs failed. Please check the logs for details."
          exit 1 
      - name: Announce success
        run: echo "All tests passed successfully!"